name: Generate Sentences

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  generate:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      OPENAI_BASE_URL: ${{ secrets.OPENAI_BASE_URL }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Or your preferred Node.js version

      - name: Install dependencies
        run: npm install

      - name: Create output directory
        run: mkdir -p sentence_output

      - name: Generate sentence files
        run: |
          for letter in {A..Z}
          do
            echo "Generating $letter.json"
            nohup timeout 1m node sentence/generate_sentences.js -i word.xlsx -l $letter -o sentence_output/$letter.json || exit 0
          done

      - name: Commit and push if changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add sentence_output/
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Automated: Generate sentence files"
            git push
          fi